name: Python CI #name of script 
#on is when we want to run , when push
#used github actions extension to resolve bugs

on: 
  push: 
    branches: 
      - 'main'

jobs: #it is what we want to run
  build: 
    runs-on: ubuntu-latest #github inbuilt server

    steps: 
        - name: Checkout code
          uses: actions/checkout@v5
        - name: Build Project
          run: echo "Building the Project"
        - name: set up python
          id:  set-python
          uses: actions/setup-python@v5
          with: 
            python-version: 3.13
        - name: install dependencies
          run:  |
            python -m pip install  --upgrade pip
            pip install -r requirements.txt
          
  test:
    runs-on:  ubuntu-latest
    needs: build  # this means this will run after build. if build failed then test and deploy will not run

    steps:
        -  name: Checkout code
           uses: actions/checkout@v5
        - name: Test Project
          run: echo "Building the Project"
        - name: set up python
          id:  set-python
          uses: actions/setup-python@v5
          with: 
            python-version: 3.13
        - name: install dependencies
          run:  |
            python -m pip install  --upgrade pip
            pip install - requirements.txt
        - name: Run tests
          run: pytest






